### ISSUE TITLE
throw an error if versionbot branch is out of date

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-ci#54]
When using versionbot check that the only difference a file in this list:

 - package.json
 - package-lock.json
 - balena.yml
 - VERSION
 - CHANGELOG.md
 - .versionbot/CHANGELOG.yml 

if there are any other files different then throw an error because this means the versionbot branch is out of date.

This is an attempt to catch cases where the versionbot check says it has completed but is not up to date with the release SHA that triggered the action.

**Comment by stathismor** [comment]
This might not be a good all-around solution for the following reasons:
1. Hard-coding filenames that might change in `versionist`
2. Missing some files, for example the rust or python ones
3. In theory, repos can implement their own versioning strategy through config and I believe that includes custom files. Not aware if we do this anywhere in balena though.

**Comment by 20k-ultra** [comment]
Thanks for the super insightful info. Regarding the hardcoding, this was going to be a best effort to catch the branch being out of sync. Meaning, it wasn't going to be perfect and catch fail positives but at the risk of never allowing out of date code being used for building a release.

Considering all the other points I am inclined now to avoid checking the files changed and instead just checking the timestamp of when the branch was updated. We can for example check that if the branch was updated like 30 minutes ago then it is out of date because the action always only runs after the versionbot check has completed which only completes after updating the branch. We could make this 30 minutes smaller to be more reasonable given what I just said about the action only running after VB finished. I might say 1 minute tbh. This time is basically the time it takes for the action to checkout the action and check last commit timestamp compared to now.

**Comment by 20k-ultra** [comment]
there's no way of reliably doing this. We just have to fix versionbot or make this action perform versioning.
